name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VORAINEWSAGENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VORAINEWSAGENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VORAINEWSAGENT_AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: voraiacr.azurecr.io
          username: ${{ secrets.VORAINEWSAGENT_REGISTRY_USERNAME }}
          password: ${{ secrets.VORAINEWSAGENT_REGISTRY_PASSWORD }}

      - name: Build and Push image to ACR
        run: |
          docker build -t voraiacr.azurecr.io/vorai-news-backend:latest .
          docker push voraiacr.azurecr.io/vorai-news-backend:latest

      - name: Deploy to Azure Container App
        uses: Azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          resourceGroup: news-headlines-rg
          containerAppName: vorai-news-agent
          acrName: voraiacr
          imageToDeploy: voraiacr.azurecr.io/vorai-news-backend:latest
