name: Trigger auto deployment for vorai-news-agent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vorai-news-agent-AutoDeployTrigger-28210d6d-4a08-41c8-b465-e5e42db36558.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VORAINEWSAGENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VORAINEWSAGENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VORAINEWSAGENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.VORAINEWSAGENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VORAINEWSAGENT_REGISTRY_PASSWORD }}
          containerAppName: vorai-news-agent
          resourceGroup: news-headlines-rg
          imageToBuild: ghcr.io/vorai-news-agent:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


